"use strict";var SummarizeWidget=(()=>{var p=Object.defineProperty;var A=Object.getOwnPropertyDescriptor;var I=Object.getOwnPropertyNames;var E=Object.prototype.hasOwnProperty;var M=(e,r)=>{for(var t in r)p(e,t,{get:r[t],enumerable:!0})},k=(e,r,t,i)=>{if(r&&typeof r=="object"||typeof r=="function")for(let n of I(r))!E.call(e,n)&&n!==t&&p(e,n,{get:()=>r[n],enumerable:!(i=A(r,n))||i.enumerable});return e};var O=e=>k(p({},"__esModule",{value:!0}),e);var Q={};M(Q,{SummarizeWidget:()=>c});var h=`<?xml version="1.0" encoding="utf-8"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
<svg fill="currentColor" width="800px" height="800px" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg"><title>OpenAI icon</title><path d="M22.2819 9.8211a5.9847 5.9847 0 0 0-.5157-4.9108 6.0462 6.0462 0 0 0-6.5098-2.9A6.0651 6.0651 0 0 0 4.9807 4.1818a5.9847 5.9847 0 0 0-3.9977 2.9 6.0462 6.0462 0 0 0 .7427 7.0966 5.98 5.98 0 0 0 .511 4.9107 6.051 6.051 0 0 0 6.5146 2.9001A5.9847 5.9847 0 0 0 13.2599 24a6.0557 6.0557 0 0 0 5.7718-4.2058 5.9894 5.9894 0 0 0 3.9977-2.9001 6.0557 6.0557 0 0 0-.7475-7.0729zm-9.022 12.6081a4.4755 4.4755 0 0 1-2.8764-1.0408l.1419-.0804 4.7783-2.7582a.7948.7948 0 0 0 .3927-.6813v-6.7369l2.02 1.1686a.071.071 0 0 1 .038.052v5.5826a4.504 4.504 0 0 1-4.4945 4.4944zm-9.6607-4.1254a4.4708 4.4708 0 0 1-.5346-3.0137l.142.0852 4.783 2.7582a.7712.7712 0 0 0 .7806 0l5.8428-3.3685v2.3324a.0804.0804 0 0 1-.0332.0615L9.74 19.9502a4.4992 4.4992 0 0 1-6.1408-1.6464zM2.3408 7.8956a4.485 4.485 0 0 1 2.3655-1.9728V11.6a.7664.7664 0 0 0 .3879.6765l5.8144 3.3543-2.0201 1.1685a.0757.0757 0 0 1-.071 0l-4.8303-2.7865A4.504 4.504 0 0 1 2.3408 7.872zm16.5963 3.8558L13.1038 8.364 15.1192 7.2a.0757.0757 0 0 1 .071 0l4.8303 2.7913a4.4944 4.4944 0 0 1-.6765 8.1042v-5.6772a.79.79 0 0 0-.407-.667zm2.0107-3.0231l-.142-.0852-4.7735-2.7818a.7759.7759 0 0 0-.7854 0L9.409 9.2297V6.8974a.0662.0662 0 0 1 .0284-.0615l4.8303-2.7866a4.4992 4.4992 0 0 1 6.6802 4.66zM8.3065 12.863l-2.02-1.1638a.0804.0804 0 0 1-.038-.0567V6.0742a4.4992 4.4992 0 0 1 7.3757-3.4537l-.142.0805L8.704 5.459a.7948.7948 0 0 0-.3927.6813zm1.0976-2.3654l2.602-1.4998 2.6069 1.4998v2.9994l-2.5974 1.4997-2.6067-1.4997Z"/></svg>`;var w=`<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Pixelmator Pro 3.6.17 -->
<svg width="1200" height="1200" viewBox="0 0 1200 1200" xmlns="http://www.w3.org/2000/svg">
    <g id="g314">
        <path id="path147" fill="#d97757" stroke="none" d="M 233.959793 800.214905 L 468.644287 668.536987 L 472.590637 657.100647 L 468.644287 650.738403 L 457.208069 650.738403 L 417.986633 648.322144 L 283.892639 644.69812 L 167.597321 639.865845 L 54.926208 633.825623 L 26.577238 627.785339 L 3.3e-05 592.751709 L 2.73832 575.27533 L 26.577238 559.248352 L 60.724873 562.228149 L 136.187973 567.382629 L 249.422867 575.194763 L 331.570496 580.026978 L 453.261841 592.671082 L 472.590637 592.671082 L 475.328857 584.859009 L 468.724915 580.026978 L 463.570557 575.194763 L 346.389313 495.785217 L 219.543671 411.865906 L 153.100723 363.543762 L 117.181267 339.060425 L 99.060455 316.107361 L 91.248367 266.01355 L 123.865784 230.093994 L 167.677887 233.073853 L 178.872513 236.053772 L 223.248367 270.201477 L 318.040283 343.570496 L 441.825592 434.738342 L 459.946411 449.798706 L 467.194672 444.64447 L 468.080597 441.020203 L 459.946411 427.409485 L 392.617493 305.718323 L 320.778564 181.932983 L 288.80542 130.630859 L 280.348999 99.865845 C 277.369171 87.221436 275.194641 76.590698 275.194641 63.624268 L 312.322174 13.20813 L 332.8591 6.604126 L 382.389313 13.20813 L 403.248352 31.328979 L 434.013519 101.71814 L 483.865753 212.537048 L 561.181274 363.221497 L 583.812134 407.919434 L 595.892639 449.315491 L 600.40271 461.959839 L 608.214783 461.959839 L 608.214783 454.711609 L 614.577271 369.825623 L 626.335632 265.61084 L 637.771851 131.516846 L 641.718201 93.745117 L 660.402832 48.483276 L 697.530334 24.000122 L 726.52356 37.852417 L 750.362549 72 L 747.060486 94.067139 L 732.886047 186.201416 L 705.100708 330.52356 L 686.979919 427.167847 L 697.530334 427.167847 L 709.61084 415.087341 L 758.496704 350.174561 L 840.644348 247.490051 L 876.885925 206.738342 L 919.167847 161.71814 L 946.308838 140.29541 L 997.61084 140.29541 L 1035.38269 196.429626 L 1018.469849 254.416199 L 965.637634 321.422852 L 921.825562 378.201538 L 859.006714 462.765259 L 819.785278 530.41626 L 823.409424 535.812073 L 832.75177 534.92627 L 974.657776 504.724915 L 1051.328979 490.872559 L 1142.818848 475.167786 L 1184.214844 494.496582 L 1188.724854 514.147644 L 1172.456421 554.335693 L 1074.604126 578.496765 L 959.838989 601.449829 L 788.939636 641.879272 L 786.845764 643.409485 L 789.261841 646.389343 L 866.255127 653.637634 L 899.194702 655.409424 L 979.812134 655.409424 L 1129.932861 666.604187 L 1169.154419 692.537109 L 1192.671265 724.268677 L 1188.724854 748.429688 L 1128.322144 779.194641 L 1046.818848 759.865845 L 856.590759 714.604126 L 791.355774 698.335754 L 782.335693 698.335754 L 782.335693 703.731567 L 836.69812 756.885986 L 936.322205 846.845581 L 1061.073975 962.81897 L 1067.436279 991.490112 L 1051.409424 1014.120911 L 1034.496704 1011.704712 L 924.885986 929.234924 L 882.604126 892.107544 L 786.845764 811.48999 L 780.483276 811.48999 L 780.483276 819.946289 L 802.550415 852.241699 L 919.087341 1027.409424 L 925.127625 1081.127686 L 916.671204 1098.604126 L 886.469849 1109.154419 L 853.288696 1103.114136 L 785.073914 1007.355835 L 714.684631 899.516785 L 657.906067 802.872498 L 650.979858 806.81897 L 617.476624 1167.704834 L 601.771851 1186.147705 L 565.530212 1200 L 535.328857 1177.046997 L 519.302124 1139.919556 L 535.328857 1066.550537 L 554.657776 970.792053 L 570.362488 894.68457 L 584.536926 800.134277 L 592.993347 768.724976 L 592.429626 766.630859 L 585.503479 767.516968 L 514.22821 865.369263 L 405.825531 1011.865906 L 320.053711 1103.677979 L 299.516815 1111.812256 L 263.919525 1093.369263 L 267.221497 1060.429688 L 287.114136 1031.114136 L 405.825531 880.107361 L 477.422913 786.52356 L 523.651062 732.483276 L 523.328918 724.671265 L 520.590698 724.671265 L 205.288605 929.395935 L 149.154434 936.644409 L 124.993355 914.01355 L 127.973183 876.885986 L 139.409409 864.80542 L 234.201385 799.570435 L 233.879227 799.8927 Z"/>
    </g>
</svg>
`;var f=`<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" id="Perplexity--Streamline-Simple-Icons" height="24" width="24">
  <desc>
    Perplexity Streamline Icon: https://streamlinehq.com
  </desc>
  <title>Perplexity</title>
  <path d="M22.3977 7.0896h-2.3106V0.0676l-7.5094 6.3542V0.1577h-1.1554v6.1966L4.4904 0v7.0896H1.6023v10.3976h2.8882V24l6.932 -6.3591v6.2005h1.1554v-6.0469l6.9318 6.1807v-6.4879h2.8882V7.0896zm-3.4657 -4.531v4.531h-5.355l5.355 -4.531zm-13.2862 0.0676 4.8691 4.4634H5.6458V2.6262zM2.7576 16.332V8.245h7.8476l-6.1149 6.1147v1.9723H2.7576zm2.8882 5.0404v-3.8852h0.0001v-2.6488l5.7763 -5.7764v7.0111l-5.7764 5.2993zm12.7086 0.0248 -5.7766 -5.1509V9.0618l5.7766 5.7766v6.5588zm2.8882 -5.0652h-1.733v-1.9723L13.3948 8.245h7.8478v8.087z" fill="currentColor" stroke-width="1"></path>
</svg>`;var L='<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M16 8.016A8.522 8.522 0 008.016 16h-.032A8.521 8.521 0 000 8.016v-.032A8.521 8.521 0 007.984 0h.032A8.522 8.522 0 0016 7.984v.032z" fill="url(#prefix__paint0_radial_980_20147)"/><defs><radialGradient id="prefix__paint0_radial_980_20147" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="matrix(16.1326 5.4553 -43.70045 129.2322 1.588 6.503)"><stop offset=".067" stop-color="#9168C0"/><stop offset=".343" stop-color="#5684D1"/><stop offset=".672" stop-color="#1BA1E3"/></radialGradient></defs></svg>';var b='<svg xmlns="http://www.w3.org/2000/svg" shape-rendering="geometricPrecision" text-rendering="geometricPrecision" image-rendering="optimizeQuality" fill-rule="evenodd" clip-rule="evenodd" viewBox="0 0 512 509.641"><path d="M115.612 0h280.776C459.975 0 512 52.026 512 115.612v278.416c0 63.587-52.025 115.613-115.612 115.613H115.612C52.026 509.641 0 457.615 0 394.028V115.612C0 52.026 52.026 0 115.612 0z"/><path fill="#fff" d="M213.235 306.019l178.976-180.002v.169l51.695-51.763c-.924 1.32-1.86 2.605-2.785 3.89-39.281 54.164-58.46 80.649-43.07 146.922l-.09-.101c10.61 45.11-.744 95.137-37.398 131.836-46.216 46.306-120.167 56.611-181.063 14.928l42.462-19.675c38.863 15.278 81.392 8.57 111.947-22.03 30.566-30.6 37.432-75.159 22.065-112.252-2.92-7.025-11.67-8.795-17.792-4.263l-124.947 92.341zm-25.786 22.437l-.033.034L68.094 435.217c7.565-10.429 16.957-20.294 26.327-30.149 26.428-27.803 52.653-55.359 36.654-94.302-21.422-52.112-8.952-113.177 30.724-152.898 41.243-41.254 101.98-51.661 152.706-30.758 11.23 4.172 21.016 10.114 28.638 15.639l-42.359 19.584c-39.44-16.563-84.629-5.299-112.207 22.313-37.298 37.308-44.84 102.003-1.128 143.81z"/></svg>';var x={chatgpt:{id:"chatgpt",name:"ChatGPT",icon:h,buildUrl:e=>`https://chat.openai.com/?q=${encodeURIComponent(e)}`},claude:{id:"claude",name:"Claude",icon:w,buildUrl:e=>`https://claude.ai/new?q=${encodeURIComponent(e)}`},perplexity:{id:"perplexity",name:"Perplexity",icon:f,buildUrl:e=>`https://www.perplexity.ai/search/new?q=${encodeURIComponent(e)}`},gemini:{id:"gemini",name:"Gemini",icon:L,buildUrl:(e,r)=>r?.geminiStyle==="search"?`https://www.google.com/search?q=${encodeURIComponent(e).replace(/%20/g,"+")}&udm=50`:`https://gemini.google.com/app?q=${encodeURIComponent(e)}`},grok:{id:"grok",name:"Grok",icon:b,buildUrl:e=>`https://x.com/i/grok?text=${encodeURIComponent(e)}`}};function S(e){return e.map(r=>x[r]).filter(Boolean)}function $(){return window.getSelection()?.toString().trim()||""}function U(){let e=document.body.cloneNode(!0);e.querySelectorAll("[data-sw-root]").forEach(i=>i.remove());let t=e.innerText||"";return t=t.replace(/\s+/g," ").trim(),t}function v(e,r){if(e.length<=r)return e;let t=e.substring(0,r),i=t.lastIndexOf(" ");return i>r*.8?t.substring(0,i)+"...":t+"..."}function B(e){let r=window.location.href,t=!1,i;if(e.preferSelection){let o=$();o&&(i=o,t=!0)}t?i=v(i,e.maxChars):e.mode==="content"?(i=e.extractContent?e.extractContent():U(),i=v(i,e.maxChars)):i=r;let n;return e.promptPrefix?e.mode==="url"&&!t?n=`${e.promptPrefix} ${r}`:n=`${e.promptPrefix}

${i}`:e.mode==="url"&&!t?n=`Summarize this page: ${r}`:t?n=`Summarize this selection from ${r}:

${i}`:n=`Summarize the following content from ${r}:

${i}`,{prompt:n,usedSelection:t}}function z(e,r){let t=x[e];if(!t)return console.warn(`[SummarizeWidget] Unknown service: ${e}`),{usedSelection:!1};let{prompt:i,usedSelection:n}=B(r),o=t.buildUrl(i,{geminiStyle:r.geminiStyle});return window.open(o,"_blank","noopener,noreferrer"),{usedSelection:n}}var _=`
.summarize-widget {
  /* Base variables - can be overridden by host */
  --sw-bg: #ffffff;
  --sw-border: #e5e7eb;
  --sw-border-radius: 10px;
  --sw-padding: 1rem;
  --sw-font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  --sw-font-size: 13px;
  --sw-text-color: #374151;
  --sw-text-secondary: #6b7280;
  --sw-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1);
  
  /* Button variables */
  --sw-button-bg: #f9fafb;
  --sw-button-hover: #f3f4f6;
  --sw-button-active: #e5e7eb;
  --sw-button-border: #e5e7eb;
  --sw-button-radius: 8px;
  --sw-button-padding: 0.5rem 0.875rem;
  --sw-button-gap: 0.5rem;
  
  /* Focus ring */
  --sw-focus-ring: #3b82f6;
  --sw-focus-ring-offset: 2px;
  
  /* Layout */
  display: inline-block;
  font-family: var(--sw-font-family);
  font-size: var(--sw-font-size);
  color: var(--sw-text-color);
  box-sizing: border-box;
  line-height: 1.5;
}

.summarize-widget *,
.summarize-widget *::before,
.summarize-widget *::after {
  box-sizing: border-box;
}

.summarize-widget__container {
  background: var(--sw-bg);
  border: 1px solid var(--sw-border);
  border-radius: var(--sw-border-radius);
  padding: var(--sw-padding);
  box-shadow: var(--sw-shadow);
}

.summarize-widget__header {
  display: flex;
  align-items: center;
  gap: 0.375rem;
  margin-bottom: 0.75rem;
  color: var(--sw-text-secondary);
  font-size: 0.75rem;
  font-weight: 500;
  letter-spacing: 0.02em;
}

.summarize-widget__header-icon {
  width: 14px;
  height: 14px;
  opacity: 0.7;
}

.summarize-widget__buttons {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
}

.summarize-widget__button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--sw-button-gap);
  padding: var(--sw-button-padding);
  background: var(--sw-button-bg);
  border: 1px solid var(--sw-button-border);
  border-radius: var(--sw-button-radius);
  color: var(--sw-text-color);
  font-family: inherit;
  font-size: inherit;
  font-weight: 500;
  cursor: pointer;
  transition: background-color 0.15s ease, border-color 0.15s ease, transform 0.1s ease;
  text-decoration: none;
  line-height: 1;
  white-space: nowrap;
}

.summarize-widget__button:hover {
  background: var(--sw-button-hover);
  border-color: #d1d5db;
}

.summarize-widget__button:active {
  background: var(--sw-button-active);
  transform: scale(0.98);
}

.summarize-widget__button:focus-visible {
  outline: 2px solid var(--sw-focus-ring);
  outline-offset: var(--sw-focus-ring-offset);
}

.summarize-widget__button-icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 16px;
  height: 16px;
  flex-shrink: 0;
}

.summarize-widget__button-icon svg {
  width: 100%;
  height: 100%;
}

.summarize-widget__button-text {
  line-height: 1;
}

/* ============================================
   DARK THEME
   ============================================ */
.summarize-widget[data-theme="dark"] {
  --sw-bg: #1f2937;
  --sw-border: #374151;
  --sw-text-color: #f9fafb;
  --sw-text-secondary: #9ca3af;
  --sw-button-bg: #374151;
  --sw-button-hover: #4b5563;
  --sw-button-active: #6b7280;
  --sw-button-border: #4b5563;
  --sw-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.3);
}

/* ============================================
   MINIMAL THEME
   ============================================ */
.summarize-widget[data-theme="minimal"] {
  /* Key Fix: Inherit color from parent container */
  --sw-text-color: inherit;
  
  /* Reset visual container styles */
  --sw-bg: transparent;
  --sw-border: transparent;
  --sw-shadow: none;
  --sw-padding: 0;
  
  /* Button Styles */
  --sw-button-bg: transparent;
  --sw-button-border: transparent;
  --sw-button-gap: 0.5rem;

  /* Dynamic Interaction States */
  
  /* Fallback for older browsers: simple opacity change */
  --sw-button-hover: rgba(128, 128, 128, 0.1); 
  --sw-button-active: rgba(128, 128, 128, 0.2);

  /* Modern browsers: Context-aware mix */
  @supports (background: color-mix(in srgb, red, blue)) {
    --sw-button-hover: color-mix(in srgb, currentColor, transparent 92%);
    --sw-button-active: color-mix(in srgb, currentColor, transparent 85%);
  }
}

.summarize-widget[data-theme="minimal"] .summarize-widget__container {
  border: none;
  box-shadow: none;
}

.summarize-widget[data-theme="minimal"] .summarize-widget__header {
  display: none;
}

/* ============================================
   COMPACT MODE (Icons Only)
   ============================================ */
.summarize-widget[data-compact="true"] .summarize-widget__header {
  display: none;
}

.summarize-widget[data-compact="true"] .summarize-widget__container {
  padding: 0.5rem;
}

.summarize-widget[data-compact="true"] .summarize-widget__buttons {
  gap: 0.375rem;
}

.summarize-widget[data-compact="true"] .summarize-widget__button {
  padding: 0.5rem;
}

.summarize-widget[data-compact="true"] .summarize-widget__button-icon {
  width: 18px;
  height: 18px;
}

.summarize-widget[data-compact="true"] .summarize-widget__button-text {
  display: none;
}

/* ============================================
   COMPACT + MINIMAL
   ============================================ */
.summarize-widget[data-theme="minimal"][data-compact="true"] .summarize-widget__container {
  padding: 0;
}

.summarize-widget[data-theme="minimal"][data-compact="true"] .summarize-widget__buttons {
  gap: 0.25rem;
}

/* ============================================
   COMPACT + DARK
   ============================================ */
.summarize-widget[data-theme="dark"][data-compact="true"] .summarize-widget__button {
  border-color: var(--sw-button-border);
}

/* ============================================
   RESPONSIVE / MOBILE
   ============================================ */
@media (max-width: 480px) {
  .summarize-widget:not([data-compact="true"]) .summarize-widget__buttons {
    flex-direction: column;
  }
  
  .summarize-widget:not([data-compact="true"]) .summarize-widget__button {
    width: 100%;
  }
}
`;function g(e){let r="summarize-widget-styles";if(e instanceof Document){if(e.getElementById(r))return;let t=e.createElement("style");t.id=r,t.textContent=_,e.head.appendChild(t)}else{let t=document.createElement("style");t.textContent=_,e.appendChild(t)}}var W=["chatgpt","perplexity","grok","gemini","claude"];function y(e){let r;if(typeof e.target=="string"){let t=document.querySelector(e.target);if(!t)throw new Error(`[SummarizeWidget] Target element not found: ${e.target}`);r=t}else r=e.target;return{target:r,mode:e.mode??"url",preferSelection:e.preferSelection??!0,maxChars:e.maxChars??4e3,services:e.services??W,theme:e.theme??"light",compact:e.compact??!1,geminiStyle:e.geminiStyle??"search",promptPrefix:e.promptPrefix,extractContent:e.extractContent,onClickService:e.onClickService}}function N(){let e=document.createElement("div");return e.className="summarize-widget__header",e.innerHTML=`
    <svg class="summarize-widget__header-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"/>
      <path d="M20 3v4"/>
      <path d="M22 5h-4"/>
      <path d="M4 17v2"/>
      <path d="M5 18H3"/>
    </svg>
    <span>Summarize with AI</span>
  `,e}function D(e,r){let t=document.createElement("button");return t.type="button",t.className="summarize-widget__button",t.setAttribute("aria-label",`Summarize with ${e.name}`),t.setAttribute("title",e.name),t.innerHTML=`
    <span class="summarize-widget__button-icon">${e.icon}</span>
    <span class="summarize-widget__button-text">${e.name}</span>
  `,t.addEventListener("click",()=>{let{usedSelection:i}=z(e.id,r);r.onClickService&&r.onClickService(e.id,{mode:r.mode,usedSelection:i})}),t}function C(e){let{target:r,services:t,theme:i,compact:n}=e,o=document.createElement("div");o.className="summarize-widget",o.setAttribute("data-theme",i),o.setAttribute("data-compact",String(n)),o.setAttribute("data-sw-root","true"),o.setAttribute("role","group"),o.setAttribute("aria-label","Summarize this page with an AI assistant");let s=document.createElement("div");s.className="summarize-widget__container",s.appendChild(N());let a=document.createElement("div");a.className="summarize-widget__buttons";let m=S(t);for(let d of m)a.appendChild(D(d,e));return s.appendChild(a),o.appendChild(s),r.innerHTML="",r.appendChild(o),o}var c={init(e){g(document);let r=y(e);return C(r)},_renderIntoShadow(e,r){g(e);let t=document.createElement("div");e.appendChild(t);let i=y({...r,target:t});return C(i)}};var G=["chatgpt","claude","perplexity","gemini","grok"];function q(e){if(e)return e.split(",").map(r=>r.trim().toLowerCase()).filter(r=>G.includes(r))}function F(e){if(e==="light"||e==="dark"||e==="minimal")return e}function j(e){if(e==="url"||e==="content")return e}function K(e){if(e==="app"||e==="search")return e}var l=class extends HTMLElement{constructor(){super();this._rendered=!1;this._shadowRoot=this.attachShadow({mode:"open"})}static get observedAttributes(){return["theme","mode","services","prefer-selection","max-chars","prompt-prefix","gemini-style","compact"]}connectedCallback(){this._render()}attributeChangedCallback(t,i,n){i!==n&&this._rendered&&this._render()}_getOptions(){let t={},i=F(this.getAttribute("theme"));i&&(t.theme=i);let n=j(this.getAttribute("mode"));n&&(t.mode=n);let o=q(this.getAttribute("services"));o?.length&&(t.services=o);let s=this.getAttribute("prefer-selection");s!==null&&(t.preferSelection=s!=="false");let a=this.getAttribute("max-chars");if(a){let u=parseInt(a,10);!isNaN(u)&&u>0&&(t.maxChars=u)}let m=this.getAttribute("prompt-prefix");m&&(t.promptPrefix=m);let d=K(this.getAttribute("gemini-style"));return d&&(t.geminiStyle=d),this.hasAttribute("compact")&&(t.compact=!0),t}_render(){this._shadowRoot.innerHTML="";let t=this._getOptions();c._renderIntoShadow(this._shadowRoot,t),this._rendered=!0}get theme(){return this.getAttribute("theme")}set theme(t){t?this.setAttribute("theme",t):this.removeAttribute("theme")}get mode(){return this.getAttribute("mode")}set mode(t){t?this.setAttribute("mode",t):this.removeAttribute("mode")}get services(){return this.getAttribute("services")}set services(t){t?this.setAttribute("services",t):this.removeAttribute("services")}get compact(){return this.hasAttribute("compact")}set compact(t){t?this.setAttribute("compact",""):this.removeAttribute("compact")}};var Z=typeof window<"u"&&typeof document<"u";Z&&"customElements"in window&&(customElements.get("summarize-with-ai")||customElements.define("summarize-with-ai",l));return O(Q);})();
// Expose init directly on the global for convenience
if(typeof window!=="undefined"){window.SummarizeWidget=SummarizeWidget.SummarizeWidget||SummarizeWidget;}
//# sourceMappingURL=summarize-widget.iife.js.map

// --- INJECTION START ---
(function() {
    console.log("Starting Precise Widget Injection (v3)...");
    
    // Safety check
    if (window.hasRunMockupWidgetv3) {
        console.warn("Widget script already ran! Refresh page to reset.");
        return;
    }
    window.hasRunMockupWidgetv3 = true;
    
    function injectWidget() {
        // 1. Try the data-testid provided by user (Most Reliable)
        let targetElement = document.querySelector('[data-testid="text-funding"]');
        
        // 2. Try class combination + text content (Fallback)
        if (!targetElement) {
            console.log("data-testid not found, trying fuzzy match...");
            const candidates = document.querySelectorAll('.text-lg.italic.text-muted-foreground');
            for (let el of candidates) {
                if (el.textContent.includes("TISC Raised US.1 Million")) {
                    targetElement = el;
                    break;
                }
            }
        }

        if (targetElement) {
            console.log("Found Target Element:", targetElement);
            targetElement.style.border = "2px solid #bada55"; // Debug highlight
            
            const container = document.createElement('div');
            container.style.cssText = 'margin: 24px 0; width: 100%; position: relative; z-index: 10;';
            container.innerHTML = '<summarize-with-ai theme="light"></summarize-with-ai>';
            
            // Insert AFTER the target element
            if (targetElement.nextSibling) {
                targetElement.parentNode.insertBefore(container, targetElement.nextSibling);
            } else {
                targetElement.parentNode.appendChild(container);
            }
            
            console.log("%c Widget Deployed! ", "background: #222; color: #bada55; font-size: 20px; padding: 10px; border-radius: 5px;");
            alert("SUCCESS: Widget injected below the funding text!");
            
            setTimeout(() => {
                container.scrollIntoView({ behavior: 'smooth', block: 'center' });
                targetElement.style.border = ""; // Remove debug highlight
            }, 500);
            
        } else {
            console.error("Could not find element with data-testid='text-funding' or matching text!");
            alert("ERROR: Still could not find the target element. Check console for details.");
        }
    }

    // Attempt injection immediately
    injectWidget();
})();
