"use strict";var SummarizeWidget=(()=>{var p=Object.defineProperty;var E=Object.getOwnPropertyDescriptor;var M=Object.getOwnPropertyNames;var k=Object.prototype.hasOwnProperty;var O=(e,r)=>{for(var t in r)p(e,t,{get:r[t],enumerable:!0})},R=(e,r,t,i)=>{if(r&&typeof r=="object"||typeof r=="function")for(let n of M(r))!k.call(e,n)&&n!==t&&p(e,n,{get:()=>r[n],enumerable:!(i=E(r,n))||i.enumerable});return e};var T=e=>R(p({},"__esModule",{value:!0}),e);var ee={};O(ee,{SummarizeWidget:()=>c});var h=`<?xml version="1.0" encoding="utf-8"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
<svg fill="currentColor" width="800px" height="800px" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg"><title>OpenAI icon</title><path d="M22.2819 9.8211a5.9847 5.9847 0 0 0-.5157-4.9108 6.0462 6.0462 0 0 0-6.5098-2.9A6.0651 6.0651 0 0 0 4.9807 4.1818a5.9847 5.9847 0 0 0-3.9977 2.9 6.0462 6.0462 0 0 0 .7427 7.0966 5.98 5.98 0 0 0 .511 4.9107 6.051 6.051 0 0 0 6.5146 2.9001A5.9847 5.9847 0 0 0 13.2599 24a6.0557 6.0557 0 0 0 5.7718-4.2058 5.9894 5.9894 0 0 0 3.9977-2.9001 6.0557 6.0557 0 0 0-.7475-7.0729zm-9.022 12.6081a4.4755 4.4755 0 0 1-2.8764-1.0408l.1419-.0804 4.7783-2.7582a.7948.7948 0 0 0 .3927-.6813v-6.7369l2.02 1.1686a.071.071 0 0 1 .038.052v5.5826a4.504 4.504 0 0 1-4.4945 4.4944zm-9.6607-4.1254a4.4708 4.4708 0 0 1-.5346-3.0137l.142.0852 4.783 2.7582a.7712.7712 0 0 0 .7806 0l5.8428-3.3685v2.3324a.0804.0804 0 0 1-.0332.0615L9.74 19.9502a4.4992 4.4992 0 0 1-6.1408-1.6464zM2.3408 7.8956a4.485 4.485 0 0 1 2.3655-1.9728V11.6a.7664.7664 0 0 0 .3879.6765l5.8144 3.3543-2.0201 1.1685a.0757.0757 0 0 1-.071 0l-4.8303-2.7865A4.504 4.504 0 0 1 2.3408 7.872zm16.5963 3.8558L13.1038 8.364 15.1192 7.2a.0757.0757 0 0 1 .071 0l4.8303 2.7913a4.4944 4.4944 0 0 1-.6765 8.1042v-5.6772a.79.79 0 0 0-.407-.667zm2.0107-3.0231l-.142-.0852-4.7735-2.7818a.7759.7759 0 0 0-.7854 0L9.409 9.2297V6.8974a.0662.0662 0 0 1 .0284-.0615l4.8303-2.7866a4.4992 4.4992 0 0 1 6.6802 4.66zM8.3065 12.863l-2.02-1.1638a.0804.0804 0 0 1-.038-.0567V6.0742a4.4992 4.4992 0 0 1 7.3757-3.4537l-.142.0805L8.704 5.459a.7948.7948 0 0 0-.3927.6813zm1.0976-2.3654l2.602-1.4998 2.6069 1.4998v2.9994l-2.5974 1.4997-2.6067-1.4997Z"/></svg>`;var w=`<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Pixelmator Pro 3.6.17 -->
<svg width="1200" height="1200" viewBox="0 0 1200 1200" xmlns="http://www.w3.org/2000/svg">
    <g id="g314">
        <path id="path147" fill="#d97757" stroke="none" d="M 233.959793 800.214905 L 468.644287 668.536987 L 472.590637 657.100647 L 468.644287 650.738403 L 457.208069 650.738403 L 417.986633 648.322144 L 283.892639 644.69812 L 167.597321 639.865845 L 54.926208 633.825623 L 26.577238 627.785339 L 3.3e-05 592.751709 L 2.73832 575.27533 L 26.577238 559.248352 L 60.724873 562.228149 L 136.187973 567.382629 L 249.422867 575.194763 L 331.570496 580.026978 L 453.261841 592.671082 L 472.590637 592.671082 L 475.328857 584.859009 L 468.724915 580.026978 L 463.570557 575.194763 L 346.389313 495.785217 L 219.543671 411.865906 L 153.100723 363.543762 L 117.181267 339.060425 L 99.060455 316.107361 L 91.248367 266.01355 L 123.865784 230.093994 L 167.677887 233.073853 L 178.872513 236.053772 L 223.248367 270.201477 L 318.040283 343.570496 L 441.825592 434.738342 L 459.946411 449.798706 L 467.194672 444.64447 L 468.080597 441.020203 L 459.946411 427.409485 L 392.617493 305.718323 L 320.778564 181.932983 L 288.80542 130.630859 L 280.348999 99.865845 C 277.369171 87.221436 275.194641 76.590698 275.194641 63.624268 L 312.322174 13.20813 L 332.8591 6.604126 L 382.389313 13.20813 L 403.248352 31.328979 L 434.013519 101.71814 L 483.865753 212.537048 L 561.181274 363.221497 L 583.812134 407.919434 L 595.892639 449.315491 L 600.40271 461.959839 L 608.214783 461.959839 L 608.214783 454.711609 L 614.577271 369.825623 L 626.335632 265.61084 L 637.771851 131.516846 L 641.718201 93.745117 L 660.402832 48.483276 L 697.530334 24.000122 L 726.52356 37.852417 L 750.362549 72 L 747.060486 94.067139 L 732.886047 186.201416 L 705.100708 330.52356 L 686.979919 427.167847 L 697.530334 427.167847 L 709.61084 415.087341 L 758.496704 350.174561 L 840.644348 247.490051 L 876.885925 206.738342 L 919.167847 161.71814 L 946.308838 140.29541 L 997.61084 140.29541 L 1035.38269 196.429626 L 1018.469849 254.416199 L 965.637634 321.422852 L 921.825562 378.201538 L 859.006714 462.765259 L 819.785278 530.41626 L 823.409424 535.812073 L 832.75177 534.92627 L 974.657776 504.724915 L 1051.328979 490.872559 L 1142.818848 475.167786 L 1184.214844 494.496582 L 1188.724854 514.147644 L 1172.456421 554.335693 L 1074.604126 578.496765 L 959.838989 601.449829 L 788.939636 641.879272 L 786.845764 643.409485 L 789.261841 646.389343 L 866.255127 653.637634 L 899.194702 655.409424 L 979.812134 655.409424 L 1129.932861 666.604187 L 1169.154419 692.537109 L 1192.671265 724.268677 L 1188.724854 748.429688 L 1128.322144 779.194641 L 1046.818848 759.865845 L 856.590759 714.604126 L 791.355774 698.335754 L 782.335693 698.335754 L 782.335693 703.731567 L 836.69812 756.885986 L 936.322205 846.845581 L 1061.073975 962.81897 L 1067.436279 991.490112 L 1051.409424 1014.120911 L 1034.496704 1011.704712 L 924.885986 929.234924 L 882.604126 892.107544 L 786.845764 811.48999 L 780.483276 811.48999 L 780.483276 819.946289 L 802.550415 852.241699 L 919.087341 1027.409424 L 925.127625 1081.127686 L 916.671204 1098.604126 L 886.469849 1109.154419 L 853.288696 1103.114136 L 785.073914 1007.355835 L 714.684631 899.516785 L 657.906067 802.872498 L 650.979858 806.81897 L 617.476624 1167.704834 L 601.771851 1186.147705 L 565.530212 1200 L 535.328857 1177.046997 L 519.302124 1139.919556 L 535.328857 1066.550537 L 554.657776 970.792053 L 570.362488 894.68457 L 584.536926 800.134277 L 592.993347 768.724976 L 592.429626 766.630859 L 585.503479 767.516968 L 514.22821 865.369263 L 405.825531 1011.865906 L 320.053711 1103.677979 L 299.516815 1111.812256 L 263.919525 1093.369263 L 267.221497 1060.429688 L 287.114136 1031.114136 L 405.825531 880.107361 L 477.422913 786.52356 L 523.651062 732.483276 L 523.328918 724.671265 L 520.590698 724.671265 L 205.288605 929.395935 L 149.154434 936.644409 L 124.993355 914.01355 L 127.973183 876.885986 L 139.409409 864.80542 L 234.201385 799.570435 L 233.879227 799.8927 Z"/>
    </g>
</svg>
`;var f=`<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" id="Perplexity--Streamline-Simple-Icons" height="24" width="24">
  <desc>
    Perplexity Streamline Icon: https://streamlinehq.com
  </desc>
  <title>Perplexity</title>
  <path d="M22.3977 7.0896h-2.3106V0.0676l-7.5094 6.3542V0.1577h-1.1554v6.1966L4.4904 0v7.0896H1.6023v10.3976h2.8882V24l6.932 -6.3591v6.2005h1.1554v-6.0469l6.9318 6.1807v-6.4879h2.8882V7.0896zm-3.4657 -4.531v4.531h-5.355l5.355 -4.531zm-13.2862 0.0676 4.8691 4.4634H5.6458V2.6262zM2.7576 16.332V8.245h7.8476l-6.1149 6.1147v1.9723H2.7576zm2.8882 5.0404v-3.8852h0.0001v-2.6488l5.7763 -5.7764v7.0111l-5.7764 5.2993zm12.7086 0.0248 -5.7766 -5.1509V9.0618l5.7766 5.7766v6.5588zm2.8882 -5.0652h-1.733v-1.9723L13.3948 8.245h7.8478v8.087z" fill="currentColor" stroke-width="1"></path>
</svg>`;var L='<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M16 8.016A8.522 8.522 0 008.016 16h-.032A8.521 8.521 0 000 8.016v-.032A8.521 8.521 0 007.984 0h.032A8.522 8.522 0 0016 7.984v.032z" fill="url(#prefix__paint0_radial_980_20147)"/><defs><radialGradient id="prefix__paint0_radial_980_20147" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="matrix(16.1326 5.4553 -43.70045 129.2322 1.588 6.503)"><stop offset=".067" stop-color="#9168C0"/><stop offset=".343" stop-color="#5684D1"/><stop offset=".672" stop-color="#1BA1E3"/></radialGradient></defs></svg>';var b='<svg xmlns="http://www.w3.org/2000/svg" shape-rendering="geometricPrecision" text-rendering="geometricPrecision" image-rendering="optimizeQuality" fill-rule="evenodd" clip-rule="evenodd" viewBox="0 0 512 509.641"><path d="M115.612 0h280.776C459.975 0 512 52.026 512 115.612v278.416c0 63.587-52.025 115.613-115.612 115.613H115.612C52.026 509.641 0 457.615 0 394.028V115.612C0 52.026 52.026 0 115.612 0z"/><path fill="#fff" d="M213.235 306.019l178.976-180.002v.169l51.695-51.763c-.924 1.32-1.86 2.605-2.785 3.89-39.281 54.164-58.46 80.649-43.07 146.922l-.09-.101c10.61 45.11-.744 95.137-37.398 131.836-46.216 46.306-120.167 56.611-181.063 14.928l42.462-19.675c38.863 15.278 81.392 8.57 111.947-22.03 30.566-30.6 37.432-75.159 22.065-112.252-2.92-7.025-11.67-8.795-17.792-4.263l-124.947 92.341zm-25.786 22.437l-.033.034L68.094 435.217c7.565-10.429 16.957-20.294 26.327-30.149 26.428-27.803 52.653-55.359 36.654-94.302-21.422-52.112-8.952-113.177 30.724-152.898 41.243-41.254 101.98-51.661 152.706-30.758 11.23 4.172 21.016 10.114 28.638 15.639l-42.359 19.584c-39.44-16.563-84.629-5.299-112.207 22.313-37.298 37.308-44.84 102.003-1.128 143.81z"/></svg>';var x={chatgpt:{id:"chatgpt",name:"ChatGPT",icon:h,buildUrl:e=>`https://chat.openai.com/?q=${encodeURIComponent(e)}`},claude:{id:"claude",name:"Claude",icon:w,buildUrl:e=>`https://claude.ai/new?q=${encodeURIComponent(e)}`},perplexity:{id:"perplexity",name:"Perplexity",icon:f,buildUrl:e=>`https://www.perplexity.ai/search/new?q=${encodeURIComponent(e)}`},gemini:{id:"gemini",name:"Gemini",icon:L,buildUrl:(e,r)=>r?.geminiStyle==="search"?`https://www.google.com/search?q=${encodeURIComponent(e).replace(/%20/g,"+")}&udm=50`:`https://gemini.google.com/app?q=${encodeURIComponent(e)}`},grok:{id:"grok",name:"Grok",icon:b,buildUrl:e=>`https://x.com/i/grok?text=${encodeURIComponent(e)}`}};function S(e){return e.map(r=>x[r]).filter(Boolean)}function B(){return window.getSelection()?.toString().trim()||""}function W(){let e=document.body.cloneNode(!0);e.querySelectorAll("[data-sw-root]").forEach(i=>i.remove());let t=e.innerText||"";return t=t.replace(/\s+/g," ").trim(),t}function v(e,r){if(e.length<=r)return e;let t=e.substring(0,r),i=t.lastIndexOf(" ");return i>r*.8?t.substring(0,i)+"...":t+"..."}function D(e){let r=window.location.href,t=!1,i;if(e.preferSelection){let o=B();o&&(i=o,t=!0)}t?i=v(i,e.maxChars):e.mode==="content"?(i=e.extractContent?e.extractContent():W(),i=v(i,e.maxChars)):i=r;let n;return e.promptPrefix?e.mode==="url"&&!t?n=`${e.promptPrefix} ${r}`:n=`${e.promptPrefix}

${i}`:e.mode==="url"&&!t?n=`Summarize this page: ${r}`:t?n=`Summarize this selection from ${r}:

${i}`:n=`Summarize the following content from ${r}:

${i}`,{prompt:n,usedSelection:t}}function z(e,r){let t=x[e];if(!t)return console.warn(`[SummarizeWidget] Unknown service: ${e}`),{usedSelection:!1};let{prompt:i,usedSelection:n}=D(r),o=t.buildUrl(i,{geminiStyle:r.geminiStyle});return window.open(o,"_blank","noopener,noreferrer"),{usedSelection:n}}var _=`
.summarize-widget {
  /* Base variables - can be overridden by host */
  --sw-bg: #ffffff;
  --sw-border: #e5e7eb;
  --sw-border-radius: 10px;
  --sw-padding: 1rem;
  --sw-font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  --sw-font-size: 13px;
  --sw-text-color: #374151;
  --sw-text-secondary: #6b7280;
  --sw-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1);
  
  /* Button variables */
  --sw-button-bg: #f9fafb;
  --sw-button-hover: #f3f4f6;
  --sw-button-active: #e5e7eb;
  --sw-button-border: #e5e7eb;
  --sw-button-radius: 8px;
  --sw-button-padding: 0.5rem 0.875rem;
  --sw-button-gap: 0.5rem;
  
  /* Focus ring */
  --sw-focus-ring: #3b82f6;
  --sw-focus-ring-offset: 2px;
  
  /* Layout */
  display: inline-block;
  font-family: var(--sw-font-family);
  font-size: var(--sw-font-size);
  color: var(--sw-text-color);
  box-sizing: border-box;
  line-height: 1.5;
}

.summarize-widget *,
.summarize-widget *::before,
.summarize-widget *::after {
  box-sizing: border-box;
}

.summarize-widget__container {
  background: var(--sw-bg);
  border: 1px solid var(--sw-border);
  border-radius: var(--sw-border-radius);
  padding: var(--sw-padding);
  box-shadow: var(--sw-shadow);
}

.summarize-widget__header {
  display: flex;
  align-items: center;
  gap: 0.375rem;
  margin-bottom: 0.75rem;
  color: var(--sw-text-secondary);
  font-size: 0.75rem;
  font-weight: 500;
  letter-spacing: 0.02em;
}

.summarize-widget__header-icon {
  width: 14px;
  height: 14px;
  opacity: 0.7;
}

.summarize-widget__buttons {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
}

.summarize-widget__button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--sw-button-gap);
  padding: var(--sw-button-padding);
  background: var(--sw-button-bg);
  border: 1px solid var(--sw-button-border);
  border-radius: var(--sw-button-radius);
  color: var(--sw-text-color);
  font-family: inherit;
  font-size: inherit;
  font-weight: 500;
  cursor: pointer;
  transition: background-color 0.15s ease, border-color 0.15s ease, transform 0.1s ease;
  text-decoration: none;
  line-height: 1;
  white-space: nowrap;
}

.summarize-widget__button:hover {
  background: var(--sw-button-hover);
  border-color: #d1d5db;
}

.summarize-widget__button:active {
  background: var(--sw-button-active);
  transform: scale(0.98);
}

.summarize-widget__button:focus-visible {
  outline: 2px solid var(--sw-focus-ring);
  outline-offset: var(--sw-focus-ring-offset);
}

.summarize-widget__button-icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 16px;
  height: 16px;
  flex-shrink: 0;
}

.summarize-widget__button-icon svg {
  width: 100%;
  height: 100%;
}

.summarize-widget__button-text {
  line-height: 1;
}

/* ============================================
   DARK THEME
   ============================================ */
.summarize-widget[data-theme="dark"] {
  --sw-bg: #1f2937;
  --sw-border: #374151;
  --sw-text-color: #f9fafb;
  --sw-text-secondary: #9ca3af;
  --sw-button-bg: #374151;
  --sw-button-hover: #4b5563;
  --sw-button-active: #6b7280;
  --sw-button-border: #4b5563;
  --sw-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.3);
}

/* ============================================
   MINIMAL THEME
   ============================================ */
.summarize-widget[data-theme="minimal"] {
  /* Key Fix: Inherit color from parent container */
  --sw-text-color: inherit;
  
  /* Reset visual container styles */
  --sw-bg: transparent;
  --sw-border: transparent;
  --sw-shadow: none;
  --sw-padding: 0;
  
  /* Button Styles */
  --sw-button-bg: transparent;
  --sw-button-border: transparent;
  --sw-button-gap: 0.5rem;

  /* Dynamic Interaction States */
  
  /* Fallback for older browsers: simple opacity change */
  --sw-button-hover: rgba(128, 128, 128, 0.1); 
  --sw-button-active: rgba(128, 128, 128, 0.2);

  /* Modern browsers: Context-aware mix */
  @supports (background: color-mix(in srgb, red, blue)) {
    --sw-button-hover: color-mix(in srgb, currentColor, transparent 92%);
    --sw-button-active: color-mix(in srgb, currentColor, transparent 85%);
  }
}

.summarize-widget[data-theme="minimal"] .summarize-widget__container {
  border: none;
  box-shadow: none;
}

.summarize-widget[data-theme="minimal"] .summarize-widget__header {
  display: none;
}

/* ============================================
   COMPACT MODE (Icons Only)
   ============================================ */
.summarize-widget[data-compact="true"] .summarize-widget__header {
  display: none;
}

.summarize-widget[data-compact="true"] .summarize-widget__container {
  padding: 0.5rem;
}

.summarize-widget[data-compact="true"] .summarize-widget__buttons {
  gap: 0.375rem;
}

.summarize-widget[data-compact="true"] .summarize-widget__button {
  padding: 0.5rem;
}

.summarize-widget[data-compact="true"] .summarize-widget__button-icon {
  width: 18px;
  height: 18px;
}

.summarize-widget[data-compact="true"] .summarize-widget__button-text {
  display: none;
}

/* ============================================
   COMPACT + MINIMAL
   ============================================ */
.summarize-widget[data-theme="minimal"][data-compact="true"] .summarize-widget__container {
  padding: 0;
}

.summarize-widget[data-theme="minimal"][data-compact="true"] .summarize-widget__buttons {
  gap: 0.25rem;
}

/* ============================================
   COMPACT + DARK
   ============================================ */
.summarize-widget[data-theme="dark"][data-compact="true"] .summarize-widget__button {
  border-color: var(--sw-button-border);
}

/* ============================================
   RESPONSIVE / MOBILE
   ============================================ */
@media (max-width: 480px) {
  .summarize-widget:not([data-compact="true"]) .summarize-widget__buttons {
    flex-direction: column;
  }
  
  .summarize-widget:not([data-compact="true"]) .summarize-widget__button {
    width: 100%;
  }
}
`;function g(e){let r="summarize-widget-styles";if(e instanceof Document){if(e.getElementById(r))return;let t=e.createElement("style");t.id=r,t.textContent=_,e.head.appendChild(t)}else{let t=document.createElement("style");t.textContent=_,e.appendChild(t)}}var N=["chatgpt","perplexity","grok","gemini","claude"],G="1.0.5",q=Date.now(),y=!1;function C(e,r){if(!y){y=!0;try{let t=new Image,i=new URLSearchParams({v:G,integration:r,lang:navigator.language||"unknown",w:String(window.screen.width),h:String(window.screen.height),theme:e.theme,mode:e.mode,compact:String(e.compact),services:e.services.join(","),prompt:e.promptPrefix?"custom":"default",maxChars:String(e.maxChars),load:String(Date.now()-q)});t.src=`https://summarizewith.vercel.app/api/beacon?${i.toString()}`,t.style.display="none",t.style.width="0",t.style.height="0"}catch{}}}function I(e){let r;if(typeof e.target=="string"){let t=document.querySelector(e.target);if(!t)throw new Error(`[SummarizeWidget] Target element not found: ${e.target}`);r=t}else r=e.target;return{target:r,mode:e.mode??"url",preferSelection:e.preferSelection??!0,maxChars:e.maxChars??4e3,services:e.services??N,theme:e.theme??"light",compact:e.compact??!1,geminiStyle:e.geminiStyle??"search",promptPrefix:e.promptPrefix,extractContent:e.extractContent,onClickService:e.onClickService}}function j(){let e=document.createElement("div");return e.className="summarize-widget__header",e.innerHTML=`
    <svg class="summarize-widget__header-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"/>
      <path d="M20 3v4"/>
      <path d="M22 5h-4"/>
      <path d="M4 17v2"/>
      <path d="M5 18H3"/>
    </svg>
    <span>Summarize with AI</span>
  `,e}function F(e,r){let t=document.createElement("button");return t.type="button",t.className="summarize-widget__button",t.setAttribute("aria-label",`Summarize with ${e.name}`),t.setAttribute("title",e.name),t.innerHTML=`
    <span class="summarize-widget__button-icon">${e.icon}</span>
    <span class="summarize-widget__button-text">${e.name}</span>
  `,t.addEventListener("click",()=>{let{usedSelection:i}=z(e.id,r);r.onClickService&&r.onClickService(e.id,{mode:r.mode,usedSelection:i})}),t}function A(e){let{target:r,services:t,theme:i,compact:n}=e,o=document.createElement("div");o.className="summarize-widget",o.setAttribute("data-theme",i),o.setAttribute("data-compact",String(n)),o.setAttribute("data-sw-root","true"),o.setAttribute("role","group"),o.setAttribute("aria-label","Summarize this page with an AI assistant");let a=document.createElement("div");a.className="summarize-widget__container",a.appendChild(j());let s=document.createElement("div");s.className="summarize-widget__buttons";let m=S(t);for(let d of m)s.appendChild(F(d,e));return a.appendChild(s),o.appendChild(a),r.innerHTML="",r.appendChild(o),o}var c={init(e){g(document);let r=I(e);return C(r,"npm"),A(r)},_renderIntoShadow(e,r){g(e);let t=document.createElement("div");e.appendChild(t);let i=I({...r,target:t});return C(i,"web-component"),A(i)}};var K=["chatgpt","claude","perplexity","gemini","grok"];function Z(e){if(e)return e.split(",").map(r=>r.trim().toLowerCase()).filter(r=>K.includes(r))}function Q(e){if(e==="light"||e==="dark"||e==="minimal")return e}function Y(e){if(e==="url"||e==="content")return e}function J(e){if(e==="app"||e==="search")return e}var l=class extends HTMLElement{constructor(){super();this._rendered=!1;this._shadowRoot=this.attachShadow({mode:"open"})}static get observedAttributes(){return["theme","mode","services","prefer-selection","max-chars","prompt-prefix","gemini-style","compact"]}connectedCallback(){this._render()}attributeChangedCallback(t,i,n){i!==n&&this._rendered&&this._render()}_getOptions(){let t={},i=Q(this.getAttribute("theme"));i&&(t.theme=i);let n=Y(this.getAttribute("mode"));n&&(t.mode=n);let o=Z(this.getAttribute("services"));o?.length&&(t.services=o);let a=this.getAttribute("prefer-selection");a!==null&&(t.preferSelection=a!=="false");let s=this.getAttribute("max-chars");if(s){let u=parseInt(s,10);!isNaN(u)&&u>0&&(t.maxChars=u)}let m=this.getAttribute("prompt-prefix");m&&(t.promptPrefix=m);let d=J(this.getAttribute("gemini-style"));return d&&(t.geminiStyle=d),this.hasAttribute("compact")&&(t.compact=!0),t}_render(){this._shadowRoot.innerHTML="";let t=this._getOptions();c._renderIntoShadow(this._shadowRoot,t),this._rendered=!0}get theme(){return this.getAttribute("theme")}set theme(t){t?this.setAttribute("theme",t):this.removeAttribute("theme")}get mode(){return this.getAttribute("mode")}set mode(t){t?this.setAttribute("mode",t):this.removeAttribute("mode")}get services(){return this.getAttribute("services")}set services(t){t?this.setAttribute("services",t):this.removeAttribute("services")}get compact(){return this.hasAttribute("compact")}set compact(t){t?this.setAttribute("compact",""):this.removeAttribute("compact")}};var X=typeof window<"u"&&typeof document<"u";X&&"customElements"in window&&(customElements.get("summarize-with-ai")||customElements.define("summarize-with-ai",l));return T(ee);})();
// Expose init directly on the global for convenience
if(typeof window!=="undefined"){window.SummarizeWidget=SummarizeWidget.SummarizeWidget||SummarizeWidget;}
//# sourceMappingURL=summarize-widget.iife.js.map

// --- SUMMARIZEWITH MOCK UP TOOL (v5 - Alignment Control) ---
(function() {
    console.log("Starting SummarizeWith Mock Up Tool v5...");

    if (document.getElementById('mockup-tool-panel')) {
        console.warn("Mockup tool already loaded!");
        return;
    }

    // --- STATE ---
    let state = {
        theme: 'light',
        compact: false,
        align: 'left', // left, center, right
        picking: false,
        dragging: null
    };

    // --- UI STYLES ---
    const styleId = 'sw-mockup-styles';
    if (!document.getElementById(styleId)) {
        const style = document.createElement('style');
        style.id = styleId;
        style.innerHTML = `
            /* Animations */
            @keyframes sw-fade-in { from { opacity: 0; transform: translateY(-10px) scale(0.98); } to { opacity: 1; transform: translateY(0) scale(1); } }

            /* Panel Container */
            #mockup-tool-panel {
                font-family: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                position: fixed;
                top: 20px;
                right: 20px;
                width: 280px;
                background: rgba(30, 30, 30, 0.65);
                backdrop-filter: saturate(180%) blur(20px);
                -webkit-backdrop-filter: saturate(180%) blur(20px);
                border: 1px solid rgba(255, 255, 255, 0.15);
                color: rgba(255, 255, 255, 0.9);
                padding: 16px;
                border-radius: 18px;
                z-index: 2147483647;
                box-shadow: 0 8px 32px rgba(0,0,0,0.35);
                animation: sw-fade-in 0.3s cubic-bezier(0.16, 1, 0.3, 1);
            }

            /* Header */
            #mockup-tool-panel h3 {
                margin: 0 0 16px 0;
                font-size: 13px;
                font-weight: 600;
                text-transform: uppercase;
                letter-spacing: 0.5px;
                color: rgba(255, 255, 255, 0.5);
                display: flex;
                align-items: center;
                gap: 8px;
            }

            .sw-control-group { margin-bottom: 16px; position: relative; }
            .sw-label { display: block; font-size: 12px; color: rgba(255,255,255,0.8); margin-bottom: 6px; font-weight: 500; }
            
            /* Theme Select */
            #mt-theme {
                width: 100%;
                padding: 8px 12px;
                background: rgba(0, 0, 0, 0.2);
                color: #fff;
                border: 1px solid rgba(255, 255, 255, 0.1);
                border-radius: 10px;
                font-size: 13px;
                appearance: none;
                cursor: pointer;
                outline: none;
            }
            #mt-theme:focus { border-color: #007bff; }
            .sw-select-wrapper::after {
                content: '';
                position: absolute;
                top: 50%;
                right: 12px;
                transform: translateY(-50%);
                border-width: 5px 4px 0 4px;
                border-style: solid;
                border-color: rgba(255,255,255,0.4) transparent transparent transparent;
                pointer-events: none;
            }

            /* Segmented Control (Alignment) */
            .sw-segmented {
                display: flex;
                background: rgba(120, 120, 128, 0.2);
                padding: 2px;
                border-radius: 8px;
            }
            .sw-seg-btn {
                flex: 1;
                padding: 6px;
                font-size: 14px;
                text-align: center;
                cursor: pointer;
                border-radius: 6px;
                color: rgba(255,255,255,0.6);
                transition: all 0.2s;
            }
            .sw-seg-btn:hover { color: #fff; }
            .sw-seg-btn.active {
                background: rgba(99, 99, 102, 0.5); /* Lighter gray for active state */
                color: #fff;
                box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            }

            /* Switch */
            .sw-switch { display: flex; align-items: center; justify-content: space-between; cursor: pointer; }
            .sw-switch-input { display: none; }
            .sw-switch-track {
                width: 42px; height: 24px; background: rgba(120, 120, 128, 0.3); border-radius: 12px; position: relative; transition: background 0.3s;
            }
            .sw-switch-thumb {
                width: 20px; height: 20px; background: #fff; border-radius: 50%; position: absolute; top: 2px; left: 2px; transition: transform 0.3s; box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            }
            .sw-switch-input:checked + .sw-switch-track { background: #34c759; }
            .sw-switch-input:checked + .sw-switch-track .sw-switch-thumb { transform: translateX(18px); }

            /* Action Buttons */
            .sw-btn {
                display: block;
                width: 100%;
                padding: 10px;
                border: 1px solid rgba(255,255,255,0.1);
                border-radius: 10px;
                font-size: 13px;
                font-weight: 600;
                cursor: pointer;
                margin-bottom: 8px;
                background: rgba(0, 122, 255, 0.6); 
                color: white;
            }
            .sw-btn:hover { background: rgba(0, 122, 255, 0.8); }
            .sw-btn.active { background: rgba(255, 149, 0, 0.8); border-color: rgba(255, 149, 0, 0.3); }
            
            #mt-clear { background: rgba(255, 59, 48, 0.15); color: #ff453a; border-color: rgba(255, 59, 48, 0.2); }
            #mt-clear:hover { background: rgba(255, 59, 48, 0.25); }
            #mt-close { position: absolute; top: 12px; right: 12px; background: transparent; border: none; color: #aaa; font-size: 18px; cursor: pointer; }

            #mt-status { font-size: 11px; color: rgba(255,255,255,0.4); text-align: center; margin-top: 5px; }

            /* Widget Wrapper */
            .mockup-wrapper {
                position: relative;
                width: fit-content; 
                display: block; 
                margin-top: 20px;
                margin-bottom: 20px;
                transition: margin 0.3s ease;
            }
            /* Alignment Classes */
            .mockup-align-left { margin-left: 0; margin-right: auto; }
            .mockup-align-center { margin-left: auto; margin-right: auto; }
            .mockup-align-right { margin-left: auto; margin-right: 0; }

            .mockup-wrapper:hover .mockup-controls {
                opacity: 1; pointer-events: auto; transform: translateY(0);
            }
            .mockup-controls {
                position: absolute; top: -30px; right: -10px; display: flex; gap: 6px;
                opacity: 0; transform: translateY(5px); transition: all 0.2s; pointer-events: none; z-index: 10000;
                background: rgba(30,30,30,0.8); padding: 4px; border-radius: 20px; backdrop-filter: blur(8px);
                border: 1px solid rgba(255,255,255,0.1);
            }
            .mockup-btn {
                width: 24px; height: 24px; border-radius: 50%; display: flex; align-items: center; justify-content: center;
                cursor: pointer; font-size: 14px;
            }
            .mockup-btn.drag { color: #0a84ff; cursor: grab; }
            .mockup-btn.delete { color: #ff453a; }
            .mockup-wrapper.is-dragging { opacity: 0.5; filter: grayscale(1); }
        `;
        document.head.appendChild(style);
    }

    // --- PANEL HTML ---
    const panel = document.createElement('div');
    panel.id = 'mockup-tool-panel';
    panel.innerHTML = `
        <h3>Mock Up Tool</h3>
        <button id="mt-close">×</button>
        
        <div class="sw-control-group">
            <span class="sw-label">THEME</span>
            <div class="sw-select-wrapper">
                <select id="mt-theme">
                    <option value="light">Light</option>
                    <option value="dark">Dark</option>
                    <option value="minimal">Minimal</option>
                </select>
            </div>
        </div>

        <div class="sw-control-group">
            <span class="sw-label">ALIGNMENT</span>
            <div class="sw-segmented">
                <div class="sw-seg-btn active" data-align="left" title="Left Align">Left</div>
                <div class="sw-seg-btn" data-align="center" title="Center Align">Center</div>
                <div class="sw-seg-btn" data-align="right" title="Right Align">Right</div>
            </div>
        </div>

        <div class="sw-control-group">
            <label class="sw-switch">
                <span class="sw-label" style="margin:0;">COMPACT</span>
                <input type="checkbox" id="mt-compact" class="sw-switch-input">
                <div class="sw-switch-track"><div class="sw-switch-thumb"></div></div>
            </label>
        </div>

        <button id="mt-pick" class="sw-btn">Place Widget</button>
        <button id="mt-clear" class="sw-btn">Clear All</button>
        
        <div id="mt-status">Ready</div>
    `;

    document.body.appendChild(panel);

    // --- EVENT REFERENCES ---
    const themeSelect = document.getElementById('mt-theme');
    const compactCheck = document.getElementById('mt-compact');
    const pickBtn = document.getElementById('mt-pick');
    const clearBtn = document.getElementById('mt-clear');
    const closeBtn = document.getElementById('mt-close');
    const statusDiv = document.getElementById('mt-status');
    const alignBtns = panel.querySelectorAll('.sw-seg-btn');

    themeSelect.addEventListener('change', (e) => state.theme = e.target.value);
    compactCheck.addEventListener('change', (e) => state.compact = e.target.checked);
    
    // Alignment Handler
    alignBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            // Update State
            state.align = btn.dataset.align;
            // Update UI
            alignBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
        });
    });

    closeBtn.addEventListener('click', () => {
         panel.remove();
         cleanupPicker();
         document.removeEventListener('dragover', onGlobalDragOver, true);
         document.removeEventListener('drop', onGlobalDrop, true);
    });

    clearBtn.addEventListener('click', () => {
        document.querySelectorAll('[data-mockup-wrapper]').forEach(el => el.remove());
        statusDiv.textContent = "All widgets cleared.";
    });

    // --- PICKER LOGIC ---
    let hoveredEl = null;

    function onMouseOver(e) {
        if (panel.contains(e.target)) return;
        if (e.target.closest('[data-mockup-wrapper]')) return;
        
        if (hoveredEl && hoveredEl !== e.target) {
           hoveredEl.style.outline = '';
        }
        hoveredEl = e.target;
        hoveredEl.style.outline = '2px solid #0a84ff';
        hoveredEl.style.cursor = 'crosshair';
        e.stopPropagation();
    }

    function onClick(e) {
        if (panel.contains(e.target)) return;
        e.preventDefault();
        e.stopPropagation();
        
        if (hoveredEl) {
            hoveredEl.style.outline = ''; 
            createWidget(hoveredEl);
            cleanupPicker();
        }
    }

    function startPicker() {
        if (state.picking) return;
        state.picking = true;
        pickBtn.classList.add('active');
        pickBtn.textContent = 'Tap to Place';
        statusDiv.textContent = "Hover over page...";
        document.addEventListener('mouseover', onMouseOver, true);
        document.addEventListener('click', onClick, true);
    }

    function cleanupPicker() {
        state.picking = false;
        pickBtn.classList.remove('active');
        pickBtn.textContent = 'Place Widget';
        statusDiv.textContent = "Ready";
        if (hoveredEl) hoveredEl.style.outline = '';
        document.removeEventListener('mouseover', onMouseOver, true);
        document.removeEventListener('click', onClick, true);
    }

    pickBtn.addEventListener('click', startPicker);

    // --- WIDGET LOGIC ---
    function createWidget(targetEl) {
        const wrapper = document.createElement('div');
        wrapper.setAttribute('data-mockup-wrapper', 'true');
        wrapper.className = 'mockup-wrapper';
        
        // Apply Alignment
        if (state.align === 'center') wrapper.classList.add('mockup-align-center');
        else if (state.align === 'right') wrapper.classList.add('mockup-align-right');
        else wrapper.classList.add('mockup-align-left');

        wrapper.style.zIndex = '10';
        
        // Controls
        const controls = document.createElement('div');
        controls.className = 'mockup-controls';
        
        const dragHandle = document.createElement('div');
        dragHandle.className = 'mockup-btn drag';
        dragHandle.innerHTML = '⋮';
        dragHandle.draggable = true;
        
        const deleteBtn = document.createElement('div');
        deleteBtn.className = 'mockup-btn delete';
        deleteBtn.innerHTML = '×';
        deleteBtn.onclick = () => wrapper.remove();
        
        controls.appendChild(dragHandle);
        controls.appendChild(deleteBtn);
        
        // Drag Events
        dragHandle.addEventListener('dragstart', (e) => {
            state.dragging = wrapper;
            wrapper.classList.add('is-dragging');
            e.dataTransfer.effectAllowed = 'move';
            e.dataTransfer.setDragImage(wrapper, 0, 0);
        });
        
        dragHandle.addEventListener('dragend', (e) => {
            state.dragging = null;
            wrapper.classList.remove('is-dragging');
            cleanDragHighlight();
        });
        
        const widget = document.createElement('summarize-with-ai');
        widget.setAttribute('theme', state.theme);
        if (state.compact) widget.setAttribute('compact', 'true');
        
        wrapper.appendChild(controls);
        wrapper.appendChild(widget);

        placeElement(targetEl, wrapper);
        
        setTimeout(() => wrapper.scrollIntoView({ behavior: 'smooth', block: 'center' }), 100);
    }

    function placeElement(targetEl, element) {
        const tagName = targetEl.tagName.toLowerCase();
        const contentTags = ['h1','h2','h3','h4','h5','h6','p','span','em','strong','img','a','li','button','input'];
        
        if (contentTags.includes(tagName) && targetEl.parentNode) {
            if (targetEl.nextSibling) {
                targetEl.parentNode.insertBefore(element, targetEl.nextSibling);
            } else {
                targetEl.parentNode.appendChild(element);
            }
        } else {
            targetEl.appendChild(element);
        }
    }

    // --- DRAG & DROP GLOBAL ---
    let dragHovered = null;

    function cleanDragHighlight() {
        if (dragHovered) {
             dragHovered.style.outline = '';
             dragHovered = null;
        }
    }

    function onGlobalDragOver(e) {
        if (!state.dragging) return;
        e.preventDefault(); 
        e.stopPropagation();
        
        const el = document.elementFromPoint(e.clientX, e.clientY);
        if (!el || el.closest('[data-mockup-wrapper]')) return;
        
        if (dragHovered !== el) {
            cleanDragHighlight();
            dragHovered = el;
            dragHovered.style.outline = '2px solid #34c759'; 
        }
    }

    function onGlobalDrop(e) {
        if (!state.dragging) return;
        e.preventDefault();
        e.stopPropagation();
        
        if (dragHovered) {
            placeElement(dragHovered, state.dragging);
            cleanDragHighlight();
        }
    }

    document.addEventListener('dragover', onGlobalDragOver, true);
    document.addEventListener('drop', onGlobalDrop, true);

    console.log("%c Mock Up Tool v5 (Alignment) Ready ", "background: #111; color: #fff; font-size: 16px; padding: 10px; border-radius: 5px;");

})();
